-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

CREATE TABLE category(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    category_name VARCHAR(30) NOT NULL,
    
)

CREATE TABLE product(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    product_name VARCHAR(30) NOT NULL,
    price DECIMAL (10,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT (10),
    category_id INTEGER FOREIGN KEY REFERENCES category(id)
)

CREATE TABLE tag(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    tag_name VARCHAR(30),

)
CREATE TABLE productTag(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    product_id INTEGER FOREIGN KEY REFERENCES product(id),
    tag_id INTEGER FOREIGN KEY REFERENCES tag(id)
)